image: node:10.15.3-alpine

stages:
  - build
  - production

build:
  stage: build
  script:
    - npm install
  tags:
    - docker
  only:
    - master

production:
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master